version: '3.9'

services:
  # ------------------------
  # PHP + Laravel Application
  # ------------------------
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile         # đã tối ưu multi-stage + alpine
      args:
        APP_ENV: ${APP_ENV:-local}
    image: plantstore-app:latest
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      # 👉 DEV: mount code để hot reload
      - ./src:/var/www/html
      # 👉 nếu production => bỏ dòng trên và COPY code trong Dockerfile
    environment:
      APP_ENV: ${APP_ENV:-local}
      CONTAINER_ROLE: app
    command: ["php-fpm"]                        # chỉ chạy php-fpm (supervisord dùng riêng nếu cần)
    networks:
      - backend
    depends_on:
      - redis

  # ------------------------
  # Nginx Web Server
  # ------------------------
  nginx:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.nginx   # nginx:alpine + config template
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-8080}:80"
    volumes:
      # 👉 DEV: mount code read-only
      - ./src:/var/www/html:ro
      # 👉 template config (dev có thể override)
      - ./.docker/conf/nginx.conf.template:/etc/nginx/templates/default.conf.template
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME:-mydev.local}
    depends_on:
      - app
    networks:
      - backend

  # ------------------------
  # Database (MySQL)
  # ------------------------
  mysql:
    image: mysql:8.1-oracle
    restart: unless-stopped
    ports:
      - "${DB_PORT_FW:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-plant_db}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-pass}
      MYSQL_ROOT_PASSWORD: "root*password"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"            # optional: mở ra ngoài cho debug
    networks:
      - backend

volumes:
  mysqldb:

networks:
  backend:
    driver: bridge
